# Generated by Django 4.2.13 on 2024-08-31 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination', '0001_initial'),
        ('examination_body', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='examination_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination_body.examinationbody'),
        ),
    ]
