# Generated by Django 4.2.13 on 2024-09-02 19:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination_paper', '0003_remove_examinationpaper_instructions'),
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='examination_paper',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='examination_paper.examinationpaper'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instructions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
