# Generated by Django 4.2.13 on 2024-08-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='instruction_number',
        ),
    ]
