# Generated by Django 4.2.13 on 2024-08-31 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination', '0001_initial'),
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('exam_duration', models.DurationField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('section', models.SlugField(blank=True, max_length=255, null=True)),
                ('subject', models.SlugField(blank=True, max_length=255, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examination')),
                ('instructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.instruction')),
            ],
            options={
                'db_table': 'examination_paper',
            },
        ),
    ]
