# Generated by Django 4.2.13 on 2024-09-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
        ('examination_paper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationpaper',
            name='section',
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='exam_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examinationpaper',
            name='instructions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructions.instruction'),
        ),
    ]
