# Generated by Django 4.2.13 on 2024-09-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination_paper', '0002_remove_examinationpaper_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationpaper',
            name='instructions',
        ),
    ]
