# Generated by Django 4.2.13 on 2024-09-01 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination_body', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationbodylogs',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_on_examination_body_action_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExaminationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_on_examination_action_by', to=settings.AUTH_USER_MODEL)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_on_examination', to='examination_body.examinationbody')),
            ],
            options={
                'db_table': 'examination_logs',
            },
        ),
    ]
