# Generated by Django 4.2.13 on 2024-09-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_initial'),
        ('logs', '0003_alter_examinationbodylogs_action_by_examinationlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationlogs',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_on_examination', to='examination.examination'),
        ),
    ]
